  GNU nano 7.2                                                                                 main.yml                                                                                           - name: Run SonarQube container
  docker_container:
    name: sonarqube
    image: sonarqube:lts-community
    ports:
      - "9000:9000"
    env:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    ulimits:
      - nofile:65536:65536
    state: started
    restart_policy: always





